/* Copyright 2017 The Chromium Authors
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file. */

#ifndef THIRD_PARTY_NGHTTP2_CHROMECONF_H_
#define THIRD_PARTY_NGHTTP2_CHROMECONF_H_

#define NGHTTP2_CR_PREFIX_SET

#define nghttp2_check_authority                                                  Cr_nghttp2_check_authority
#define nghttp2_check_header_name                                                Cr_nghttp2_check_header_name
#define nghttp2_check_header_value                                               Cr_nghttp2_check_header_value
#define nghttp2_check_header_value_rfc9113                                       Cr_nghttp2_check_header_value_rfc9113
#define nghttp2_check_method                                                     Cr_nghttp2_check_method
#define nghttp2_check_path                                                       Cr_nghttp2_check_path
#define nghttp2_extpri_parse_priority                                            Cr_nghttp2_extpri_parse_priority
#define nghttp2_hd_deflate_bound                                                 Cr_nghttp2_hd_deflate_bound
#define nghttp2_hd_deflate_change_table_size                                     Cr_nghttp2_hd_deflate_change_table_size
#define nghttp2_hd_deflate_del                                                   Cr_nghttp2_hd_deflate_del
#define nghttp2_hd_deflate_get_dynamic_table_size                                Cr_nghttp2_hd_deflate_get_dynamic_table_size
#define nghttp2_hd_deflate_get_max_dynamic_table_size                            Cr_nghttp2_hd_deflate_get_max_dynamic_table_size
#define nghttp2_hd_deflate_get_num_table_entries                                 Cr_nghttp2_hd_deflate_get_num_table_entries
#define nghttp2_hd_deflate_get_table_entry                                       Cr_nghttp2_hd_deflate_get_table_entry
#define nghttp2_hd_deflate_hd                                                    Cr_nghttp2_hd_deflate_hd
#define nghttp2_hd_deflate_hd2                                                   Cr_nghttp2_hd_deflate_hd2
#define nghttp2_hd_deflate_hd_vec                                                Cr_nghttp2_hd_deflate_hd_vec
#define nghttp2_hd_deflate_hd_vec2                                               Cr_nghttp2_hd_deflate_hd_vec2
#define nghttp2_hd_deflate_new                                                   Cr_nghttp2_hd_deflate_new
#define nghttp2_hd_deflate_new2                                                  Cr_nghttp2_hd_deflate_new2
#define nghttp2_hd_inflate_change_table_size                                     Cr_nghttp2_hd_inflate_change_table_size
#define nghttp2_hd_inflate_del                                                   Cr_nghttp2_hd_inflate_del
#define nghttp2_hd_inflate_end_headers                                           Cr_nghttp2_hd_inflate_end_headers
#define nghttp2_hd_inflate_get_dynamic_table_size                                Cr_nghttp2_hd_inflate_get_dynamic_table_size
#define nghttp2_hd_inflate_get_max_dynamic_table_size                            Cr_nghttp2_hd_inflate_get_max_dynamic_table_size
#define nghttp2_hd_inflate_get_num_table_entries                                 Cr_nghttp2_hd_inflate_get_num_table_entries
#define nghttp2_hd_inflate_get_table_entry                                       Cr_nghttp2_hd_inflate_get_table_entry
#define nghttp2_hd_inflate_hd                                                    Cr_nghttp2_hd_inflate_hd
#define nghttp2_hd_inflate_hd2                                                   Cr_nghttp2_hd_inflate_hd2
#define nghttp2_hd_inflate_hd3                                                   Cr_nghttp2_hd_inflate_hd3
#define nghttp2_hd_inflate_new                                                   Cr_nghttp2_hd_inflate_new
#define nghttp2_hd_inflate_new2                                                  Cr_nghttp2_hd_inflate_new2
#define nghttp2_http2_strerror                                                   Cr_nghttp2_http2_strerror
#define nghttp2_is_fatal                                                         Cr_nghttp2_is_fatal
#define nghttp2_nv_compare_name                                                  Cr_nghttp2_nv_compare_name
#define nghttp2_option_del                                                       Cr_nghttp2_option_del
#define nghttp2_option_new                                                       Cr_nghttp2_option_new
#define nghttp2_option_set_builtin_recv_extension_type                           Cr_nghttp2_option_set_builtin_recv_extension_type
#define nghttp2_option_set_glitch_rate_limit                                     Cr_nghttp2_option_set_glitch_rate_limit
#define nghttp2_option_set_max_continuations                                     Cr_nghttp2_option_set_max_continuations
#define nghttp2_option_set_max_deflate_dynamic_table_size                        Cr_nghttp2_option_set_max_deflate_dynamic_table_size
#define nghttp2_option_set_max_outbound_ack                                      Cr_nghttp2_option_set_max_outbound_ack
#define nghttp2_option_set_max_reserved_remote_streams                           Cr_nghttp2_option_set_max_reserved_remote_streams
#define nghttp2_option_set_max_send_header_block_length                          Cr_nghttp2_option_set_max_send_header_block_length
#define nghttp2_option_set_max_settings                                          Cr_nghttp2_option_set_max_settings
#define nghttp2_option_set_no_auto_ping_ack                                      Cr_nghttp2_option_set_no_auto_ping_ack
#define nghttp2_option_set_no_auto_window_update                                 Cr_nghttp2_option_set_no_auto_window_update
#define nghttp2_option_set_no_closed_streams                                     Cr_nghttp2_option_set_no_closed_streams
#define nghttp2_option_set_no_http_messaging                                     Cr_nghttp2_option_set_no_http_messaging
#define nghttp2_option_set_no_recv_client_magic                                  Cr_nghttp2_option_set_no_recv_client_magic
#define nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation         Cr_nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation
#define nghttp2_option_set_peer_max_concurrent_streams                           Cr_nghttp2_option_set_peer_max_concurrent_streams
#define nghttp2_option_set_server_fallback_rfc7540_priorities                    Cr_nghttp2_option_set_server_fallback_rfc7540_priorities
#define nghttp2_option_set_stream_reset_rate_limit                               Cr_nghttp2_option_set_stream_reset_rate_limit
#define nghttp2_option_set_user_recv_extension_type                              Cr_nghttp2_option_set_user_recv_extension_type
#define nghttp2_pack_settings_payload                                            Cr_nghttp2_pack_settings_payload
#define nghttp2_pack_settings_payload2                                           Cr_nghttp2_pack_settings_payload2
#define nghttp2_priority_spec_check_default                                      Cr_nghttp2_priority_spec_check_default
#define nghttp2_priority_spec_default_init                                       Cr_nghttp2_priority_spec_default_init
#define nghttp2_priority_spec_init                                               Cr_nghttp2_priority_spec_init
#define nghttp2_rcbuf_decref                                                     Cr_nghttp2_rcbuf_decref
#define nghttp2_rcbuf_get_buf                                                    Cr_nghttp2_rcbuf_get_buf
#define nghttp2_rcbuf_incref                                                     Cr_nghttp2_rcbuf_incref
#define nghttp2_rcbuf_is_static                                                  Cr_nghttp2_rcbuf_is_static
#define nghttp2_select_alpn                                                      Cr_nghttp2_select_alpn
#define nghttp2_select_next_protocol                                             Cr_nghttp2_select_next_protocol
#define nghttp2_session_callbacks_del                                            Cr_nghttp2_session_callbacks_del
#define nghttp2_session_callbacks_new                                            Cr_nghttp2_session_callbacks_new
#define nghttp2_session_callbacks_set_before_frame_send_callback                 Cr_nghttp2_session_callbacks_set_before_frame_send_callback
#define nghttp2_session_callbacks_set_data_source_read_length_callback           Cr_nghttp2_session_callbacks_set_data_source_read_length_callback
#define nghttp2_session_callbacks_set_data_source_read_length_callback2          Cr_nghttp2_session_callbacks_set_data_source_read_length_callback2
#define nghttp2_session_callbacks_set_error_callback                             Cr_nghttp2_session_callbacks_set_error_callback
#define nghttp2_session_callbacks_set_error_callback2                            Cr_nghttp2_session_callbacks_set_error_callback2
#define nghttp2_session_callbacks_set_on_begin_frame_callback                    Cr_nghttp2_session_callbacks_set_on_begin_frame_callback
#define nghttp2_session_callbacks_set_on_begin_headers_callback                  Cr_nghttp2_session_callbacks_set_on_begin_headers_callback
#define nghttp2_session_callbacks_set_on_data_chunk_recv_callback                Cr_nghttp2_session_callbacks_set_on_data_chunk_recv_callback
#define nghttp2_session_callbacks_set_on_extension_chunk_recv_callback           Cr_nghttp2_session_callbacks_set_on_extension_chunk_recv_callback
#define nghttp2_session_callbacks_set_on_frame_not_send_callback                 Cr_nghttp2_session_callbacks_set_on_frame_not_send_callback
#define nghttp2_session_callbacks_set_on_frame_recv_callback                     Cr_nghttp2_session_callbacks_set_on_frame_recv_callback
#define nghttp2_session_callbacks_set_on_frame_send_callback                     Cr_nghttp2_session_callbacks_set_on_frame_send_callback
#define nghttp2_session_callbacks_set_on_header_callback                         Cr_nghttp2_session_callbacks_set_on_header_callback
#define nghttp2_session_callbacks_set_on_header_callback2                        Cr_nghttp2_session_callbacks_set_on_header_callback2
#define nghttp2_session_callbacks_set_on_invalid_frame_recv_callback             Cr_nghttp2_session_callbacks_set_on_invalid_frame_recv_callback
#define nghttp2_session_callbacks_set_on_invalid_header_callback                 Cr_nghttp2_session_callbacks_set_on_invalid_header_callback
#define nghttp2_session_callbacks_set_on_invalid_header_callback2                Cr_nghttp2_session_callbacks_set_on_invalid_header_callback2
#define nghttp2_session_callbacks_set_on_stream_close_callback                   Cr_nghttp2_session_callbacks_set_on_stream_close_callback
#define nghttp2_session_callbacks_set_pack_extension_callback                    Cr_nghttp2_session_callbacks_set_pack_extension_callback
#define nghttp2_session_callbacks_set_pack_extension_callback2                   Cr_nghttp2_session_callbacks_set_pack_extension_callback2
#define nghttp2_session_callbacks_set_rand_callback                              Cr_nghttp2_session_callbacks_set_rand_callback
#define nghttp2_session_callbacks_set_recv_callback                              Cr_nghttp2_session_callbacks_set_recv_callback
#define nghttp2_session_callbacks_set_recv_callback2                             Cr_nghttp2_session_callbacks_set_recv_callback2
#define nghttp2_session_callbacks_set_select_padding_callback                    Cr_nghttp2_session_callbacks_set_select_padding_callback
#define nghttp2_session_callbacks_set_select_padding_callback2                   Cr_nghttp2_session_callbacks_set_select_padding_callback2
#define nghttp2_session_callbacks_set_send_callback                              Cr_nghttp2_session_callbacks_set_send_callback
#define nghttp2_session_callbacks_set_send_callback2                             Cr_nghttp2_session_callbacks_set_send_callback2
#define nghttp2_session_callbacks_set_send_data_callback                         Cr_nghttp2_session_callbacks_set_send_data_callback
#define nghttp2_session_callbacks_set_unpack_extension_callback                  Cr_nghttp2_session_callbacks_set_unpack_extension_callback
#define nghttp2_session_change_extpri_stream_priority                            Cr_nghttp2_session_change_extpri_stream_priority
#define nghttp2_session_change_stream_priority                                   Cr_nghttp2_session_change_stream_priority
#define nghttp2_session_check_request_allowed                                    Cr_nghttp2_session_check_request_allowed
#define nghttp2_session_check_server_session                                     Cr_nghttp2_session_check_server_session
#define nghttp2_session_client_new                                               Cr_nghttp2_session_client_new
#define nghttp2_session_client_new2                                              Cr_nghttp2_session_client_new2
#define nghttp2_session_client_new3                                              Cr_nghttp2_session_client_new3
#define nghttp2_session_consume                                                  Cr_nghttp2_session_consume
#define nghttp2_session_consume_connection                                       Cr_nghttp2_session_consume_connection
#define nghttp2_session_consume_stream                                           Cr_nghttp2_session_consume_stream
#define nghttp2_session_create_idle_stream                                       Cr_nghttp2_session_create_idle_stream
#define nghttp2_session_del                                                      Cr_nghttp2_session_del
#define nghttp2_session_find_stream                                              Cr_nghttp2_session_find_stream
#define nghttp2_session_get_effective_local_window_size                          Cr_nghttp2_session_get_effective_local_window_size
#define nghttp2_session_get_effective_recv_data_length                           Cr_nghttp2_session_get_effective_recv_data_length
#define nghttp2_session_get_extpri_stream_priority                               Cr_nghttp2_session_get_extpri_stream_priority
#define nghttp2_session_get_hd_deflate_dynamic_table_size                        Cr_nghttp2_session_get_hd_deflate_dynamic_table_size
#define nghttp2_session_get_hd_inflate_dynamic_table_size                        Cr_nghttp2_session_get_hd_inflate_dynamic_table_size
#define nghttp2_session_get_last_proc_stream_id                                  Cr_nghttp2_session_get_last_proc_stream_id
#define nghttp2_session_get_local_settings                                       Cr_nghttp2_session_get_local_settings
#define nghttp2_session_get_local_window_size                                    Cr_nghttp2_session_get_local_window_size
#define nghttp2_session_get_next_stream_id                                       Cr_nghttp2_session_get_next_stream_id
#define nghttp2_session_get_outbound_queue_size                                  Cr_nghttp2_session_get_outbound_queue_size
#define nghttp2_session_get_remote_settings                                      Cr_nghttp2_session_get_remote_settings
#define nghttp2_session_get_remote_window_size                                   Cr_nghttp2_session_get_remote_window_size
#define nghttp2_session_get_root_stream                                          Cr_nghttp2_session_get_root_stream
#define nghttp2_session_get_stream_effective_local_window_size                   Cr_nghttp2_session_get_stream_effective_local_window_size
#define nghttp2_session_get_stream_effective_recv_data_length                    Cr_nghttp2_session_get_stream_effective_recv_data_length
#define nghttp2_session_get_stream_local_close                                   Cr_nghttp2_session_get_stream_local_close
#define nghttp2_session_get_stream_local_window_size                             Cr_nghttp2_session_get_stream_local_window_size
#define nghttp2_session_get_stream_remote_close                                  Cr_nghttp2_session_get_stream_remote_close
#define nghttp2_session_get_stream_remote_window_size                            Cr_nghttp2_session_get_stream_remote_window_size
#define nghttp2_session_get_stream_user_data                                     Cr_nghttp2_session_get_stream_user_data
#define nghttp2_session_mem_recv                                                 Cr_nghttp2_session_mem_recv
#define nghttp2_session_mem_recv2                                                Cr_nghttp2_session_mem_recv2
#define nghttp2_session_mem_send                                                 Cr_nghttp2_session_mem_send
#define nghttp2_session_mem_send2                                                Cr_nghttp2_session_mem_send2
#define nghttp2_session_recv                                                     Cr_nghttp2_session_recv
#define nghttp2_session_resume_data                                              Cr_nghttp2_session_resume_data
#define nghttp2_session_send                                                     Cr_nghttp2_session_send
#define nghttp2_session_server_new                                               Cr_nghttp2_session_server_new
#define nghttp2_session_server_new2                                              Cr_nghttp2_session_server_new2
#define nghttp2_session_server_new3                                              Cr_nghttp2_session_server_new3
#define nghttp2_session_set_local_window_size                                    Cr_nghttp2_session_set_local_window_size
#define nghttp2_session_set_next_stream_id                                       Cr_nghttp2_session_set_next_stream_id
#define nghttp2_session_set_stream_user_data                                     Cr_nghttp2_session_set_stream_user_data
#define nghttp2_session_set_user_data                                            Cr_nghttp2_session_set_user_data
#define nghttp2_session_terminate_session                                        Cr_nghttp2_session_terminate_session
#define nghttp2_session_terminate_session2                                       Cr_nghttp2_session_terminate_session2
#define nghttp2_session_upgrade                                                  Cr_nghttp2_session_upgrade
#define nghttp2_session_upgrade2                                                 Cr_nghttp2_session_upgrade2
#define nghttp2_session_want_read                                                Cr_nghttp2_session_want_read
#define nghttp2_session_want_write                                               Cr_nghttp2_session_want_write
#define nghttp2_set_debug_vprintf_callback                                       Cr_nghttp2_set_debug_vprintf_callback
#define nghttp2_stream_get_first_child                                           Cr_nghttp2_stream_get_first_child
#define nghttp2_stream_get_next_sibling                                          Cr_nghttp2_stream_get_next_sibling
#define nghttp2_stream_get_parent                                                Cr_nghttp2_stream_get_parent
#define nghttp2_stream_get_previous_sibling                                      Cr_nghttp2_stream_get_previous_sibling
#define nghttp2_stream_get_state                                                 Cr_nghttp2_stream_get_state
#define nghttp2_stream_get_stream_id                                             Cr_nghttp2_stream_get_stream_id
#define nghttp2_stream_get_sum_dependency_weight                                 Cr_nghttp2_stream_get_sum_dependency_weight
#define nghttp2_stream_get_weight                                                Cr_nghttp2_stream_get_weight
#define nghttp2_strerror                                                         Cr_nghttp2_strerror
#define nghttp2_submit_altsvc                                                    Cr_nghttp2_submit_altsvc
#define nghttp2_submit_data                                                      Cr_nghttp2_submit_data
#define nghttp2_submit_data2                                                     Cr_nghttp2_submit_data2
#define nghttp2_submit_extension                                                 Cr_nghttp2_submit_extension
#define nghttp2_submit_goaway                                                    Cr_nghttp2_submit_goaway
#define nghttp2_submit_headers                                                   Cr_nghttp2_submit_headers
#define nghttp2_submit_origin                                                    Cr_nghttp2_submit_origin
#define nghttp2_submit_ping                                                      Cr_nghttp2_submit_ping
#define nghttp2_submit_priority                                                  Cr_nghttp2_submit_priority
#define nghttp2_submit_priority_update                                           Cr_nghttp2_submit_priority_update
#define nghttp2_submit_push_promise                                              Cr_nghttp2_submit_push_promise
#define nghttp2_submit_request                                                   Cr_nghttp2_submit_request
#define nghttp2_submit_request2                                                  Cr_nghttp2_submit_request2
#define nghttp2_submit_response                                                  Cr_nghttp2_submit_response
#define nghttp2_submit_response2                                                 Cr_nghttp2_submit_response2
#define nghttp2_submit_rst_stream                                                Cr_nghttp2_submit_rst_stream
#define nghttp2_submit_settings                                                  Cr_nghttp2_submit_settings
#define nghttp2_submit_shutdown_notice                                           Cr_nghttp2_submit_shutdown_notice
#define nghttp2_submit_trailer                                                   Cr_nghttp2_submit_trailer
#define nghttp2_submit_window_update                                             Cr_nghttp2_submit_window_update
#define nghttp2_version                                                          Cr_nghttp2_version

#endif /* THIRD_PARTY_NGHTTP2_CHROMECONF_H_ */
